version: '3.5'
services:
  postgres:
    image: postgres:latest
    container_name: scrolliris-postgres
    networks:
      - scrolliris_backend
    environment:
      - POSTGRES_USER=scrolliris
      - POSTGRES_PASSWORD=scrolliris
      - POSTGRES_DB=scrolliris_development
    volumes:
      - scrolliris-postgres-data:/var/lib/postgres/data
    depends_on:
      - postgres-data
    ports:
      - '5432:5432'

  postgres-data:
    build:
      context: ./srv/
      dockerfile: Dockerfile-postgres-data
    container_name: scrolliris-postgres-data
    volumes:
      - ./var/lib/postgres/data:/var/lib/postgres/data

  redis:
    image: redis:latest
    container_name: scrolliris-redis
    networks:
      - scrolliris_backend
    ports:
      - '6379:6379'

  memcached:
    image: memcached:latest
    container_name: scrolliris-memcached
    networks:
      - scrolliris_backend
    entrypoint:
      - memcached
      - -m 128
    ports:
      - '11211:11211'

  console:
    build:
      context: ./srv/scrolliris-console
      dockerfile: Dockerfile
      args:
        HTTP_HOST: 0.0.0.0
        HTTP_PORT: 5000
        HOST: 0.0.0.0
        PORT: 5000
        ENV: development
    container_name: scrolliris-console
    networks:
      - scrolliris_backend
    volumes:
      - ./log/scrolliris-console:/app/tmp/log
    depends_on:
      - postgres
      - redis
      - memcached
    env_file: ./srv/scrolliris-console/.env
    ports:
      - '5000:5000'

volumes:
  scrolliris-postgres-data:

networks:
  scrolliris_backend:
    name: scrolliris_backend
    driver: bridge
    external: true
  default:
    external:
      name: scrolliris_backend
